language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt551-trusty'
    packages:
    - qt55base

script:
  - source /opt/qt55/bin/qt55-env.s
  - qmake redshift-qt.pro
  - make

os:
  - linux
