.\" Manpage for redshift-qt.
.\" Contact valeriy.malov@example.com to correct errors or typos.
.TH man 8 "4 Nov 2019" "0.5" "redshift-qt man page"
.SH NAME
redshift-qt \- Adjusts the color temperature of your screen with Qt5 integration
.SH SYNOPSIS
redshift-qt [OPTIONS]
.SH DESCRIPTION
Redshift-qt runs redshift on the back, the color temperature is set according to
 the position of the sun. A different color temperature is set during night and
 daytime. During twilight and early morning, the color temperature transitions
 smoothly from night to daytime temperature to allow your eyes to slowly adapt.
.SH OPTIONS
redshift-qt takes the same options as redshift.
.SH SEE ALSO
redshift
.SH BUGS
No known bugs.
.SH AUTHOR
Valerii Malov <jazzvoid@gmail.com>
